### ISSUE TITLE
TOPページのコントローラー

### ISSUE THREAD

**Issue by qtro** [IH31/Sugukuru#2]
TOPページ用コントローラーの作成。

・商品の種別選択から種類別商品の表示

・キーワード検索

・ログイン処理へディスパッチ

・カート処理へディスパッチ

**Comment by YuOikawa** [comment]
在庫管理

**Comment by qtro** [comment]
カート・ログインは別Controllerで処理

**Comment by qtro** [comment]
ひとまずClose
